name: Step 2

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_3_FILE: ".github/steps/3-fix-broken-sidebar.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.3.0

  
  validate_commit_reference:
    name: Validate Commit Reference
    runs-on: ubuntu-latest
    needs: [find_exercise]
    outputs:
      commit_check: ${{ steps.check_commit_id.outcome }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Saved Commit ID
        id: get_commit_id
        run: |
          echo "commit_id=$(cat .github/files/SIDEBARCOMMIT)" >> $GITHUB_OUTPUT
      
      - name: Check if commit ID is in comment
        id: check_commit_id
        uses: skills/action-keyphrase-checker@v1
        with:
          text: ${{ github.event.comment.body }}
          keyphrase: ${{ steps.get_commit_id.outputs.commit_id }}
          case-sensitive: false
          minimum-occurrences: 1

  check_step_work:
    name: Check Step Work
    runs-on: ubuntu-latest
    needs: [find_exercise, validate_commit_reference]
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.3.0

      - name: Comment - Checking your work
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment - Missing commit ID
        if: needs.validate_commit_reference.outputs.commit_check != 'success'
        run: |
          gh issue comment "$ISSUE_URL" \
            --body: >
              **Hmm, I couldn’t find the commit ID in your comment.**
              Please make sure to follow the instructions in the step above.
          exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build message - step finished
        id: build-message-step-finish
        uses: skills/action-text-variables@v1
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          template-vars: |
            next_step_number=3

      - name: Update comment - step finished
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "${{ steps.build-message-step-finish.outputs.updated-text }}" \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  post_next_step_content:
    name: Post Next Step Content
    needs: [find_exercise, validate_commit_reference, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.3.0

      - name: Post Step Content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file ${{ env.STEP_3_FILE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Watching Progress Comment
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Transition to Next Workflow
        run: |
          gh workflow disable "Step 2"
          gh workflow enable "Step 3"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
