name: Step 2

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_3_FILE: ".github/steps/3-fix-broken-sidebar.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.3.0

  
  validate_commit_reference:
    name: Validate Commit Reference
    runs-on: ubuntu-latest
    needs: [find_exercise]
    outputs:
      commit_id: ${{ steps.get_commit_id.outputs.commit_id }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - id: get_commit_id
        run: |
          echo "commit_id=$(cat .github/files/SIDEBARCOMMIT)" >> $GITHUB_OUTPUT

  check_step_work:
    name: Check Step Work
    runs-on: ubuntu-latest
    needs: [find_exercise, validate_commit_reference]
    if: contains(github.event.comment.body, ${{ needs.validate_commit_reference.outputs.commit_id }})
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.3.0

      - name: Update Comment - Checking Work
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  post_next_step_content:
    name: Post Next Step Content
    needs: [find_exercise, validate_commit_reference, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.3.0

      - name: Post Step Content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file ${{ env.STEP_3_FILE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post Watching Progress Comment
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Transition to Next Workflow
        run: |
          gh workflow disable "Step 2"
          gh workflow enable "Step 3"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
