name: Step 3

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - closed

permissions:
  contents: write
  actions: write
  issues: write

env:
  FINISH_FILE: ".github/steps/x-finish.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.3.0

  check_step_work:
    name: Check Step Work
    needs: find_exercise
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate pull request state
        id: validate_pr
        run: |
          echo "valid=true" >> $GITHUB_OUTPUT

          if [ "${{ github.event.repository.is_template }}" = "true" ]; then
            echo "valid=false" >> $GITHUB_OUTPUT
          elif [ "${{ github.head_ref }}" != "fix-sidebar" ]; then
            echo "valid=false" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.pull_request.merged }}" != "true" ]; then
            echo "valid=false" >> $GITHUB_OUTPUT
          elif ! echo "${{ github.event.pull_request.body }}" | grep -iq "Closes"; then
            echo "valid=false" >> $GITHUB_OUTPUT
          fi

      - name: Update comment - PR not valid
        if: steps.validate_pr.outputs.valid == 'false'
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "**Looks like your pull request isn't quite ready yet.**  
            Please ensure the following:
            - Your PR is from the `fix-sidebar` branch
            - The PR is merged
            - The body contains the keyword `Closes` (case-insensitive)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail job if PR is invalid
        if: steps.validate_pr.outputs.valid == 'false'
        run: exit 1

      - name: Update Comment - Checking Work
        if: steps.validate_pr.outputs.valid == 'true'
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post_review_content:
    name: Post Review Content
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.3.0

      - name: Create Comment - Add Review Content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "$FINISH_FILE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable Current Workflow
        run: gh workflow disable "${{ github.workflow }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish_exercise:
    name: Finish Exercise
    needs: post_review_content
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@v0.4.0
    with:
      issue-url: ${{ github.event.pull_request.issue_url }}
