name: Step 3

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - closed

permissions:
  contents: write
  actions: write
  issues: write

env:
  FINISH_FILE: ".github/steps/x-finish.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.3.0

  check_step_work:
    name: Check Step Work
    needs: find_exercise
    runs-on: ubuntu-latest
    if: |
      !github.event.repository.is_template &&
      github.head_ref == 'fix-sidebar' &&
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.body, 'Closes')
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Comment - Checking Work
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post_review_content:
    name: Post Review Content
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.3.0

      - name: Create Comment - Add Review Content
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "$FINISH_FILE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      - name: Disable Current Workflow
        run: gh workflow disable "${{ github.workflow }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish_exercise:
    name: Finish Exercise
    needs: post_review_content
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@v0.4.0
    with:
      issue-url: ${{ github.event.pull_request.issue_url }}
